version: "2"

run:
  timeout: 1m
  modules-download-mode: mod

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    - bidichk
    - gosec
    - lll
    - misspell
    - revive
    - unparam
    - unused
    - godox

  settings:
    bidichk:
      left-to-right-embedding: true
      right-to-left-embedding: true
      pop-directional-formatting: true
      left-to-right-override: true
      right-to-left-override: true
      left-to-right-isolate: true
      right-to-left-isolate: true
      first-strong-isolate: true
      pop-directional-isolate: true

    godox:
      keywords:
        - NOTE
        - OPTIMIZE
        - HACK

    gosec:
      includes:
        - G401
        - G306
        - G101
        - G102
        - G103
      severity: medium
      confidence: medium

    lll:
      line-length: 120
      tab-width: 2

    misspell:
      locale: US

    revive:
      severity: warning
      rules:
        - name: indent-error-flow
          severity: warning

    unparam:
      check-exported: true

  exclusions:
    paths:
      - "tools/.*"
      - "utils/.*"
    rules:
      - path: _test\.go$
        linters:
          - lll
          - unparam
          - gosec

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: false
