repos:
- repo: git://github.com/dnephin/pre-commit-golang
  rev: v0.4.0
  hooks:
    - id: go-fmt
    - id: go-unit-tests
    - id: go-imports
    - id: validate-toml
    - id: no-go-testing
    - id: go-build
    - id: go-mod-tidy

